# Generated by Django 3.1.1 on 2020-11-30 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubserv', '0002_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='userNameSub',
            new_name='authorSub',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='post',
            new_name='postSub',
        ),
    ]
