# Generated by Django 3.1.1 on 2020-12-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubserv', '0003_auto_20201130_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-idPost'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
