# Generated by Django 3.1.1 on 2020-12-01 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ubserv', '0005_auto_20201202_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-idPost'], 'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='news',
            name='idPost',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='idPost'),
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('idScr', models.AutoField(primary_key=True, serialize=False, verbose_name='idScr')),
                ('authorScr', models.CharField(max_length=255, verbose_name='Автор подписки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец подписки')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписка',
                'db_table': 'Subscription',
                'ordering': ['idScr'],
            },
        ),
    ]
