# Generated by Django 3.1.1 on 2020-12-02 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubserv', '0006_auto_20201202_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='authorScr',
            new_name='authorSub',
        ),
    ]
