# Generated by Django 3.1.1 on 2020-12-02 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ubserv', '0007_auto_20201202_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='authorSub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор пдписки'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userow', to=settings.AUTH_USER_MODEL, verbose_name='Владелец подписки'),
        ),
    ]
