# Generated by Django 3.1.1 on 2020-12-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubserv', '0008_auto_20201202_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='authorSub',
            field=models.CharField(max_length=255, verbose_name='Автор пдписки'),
        ),
    ]
